package com.cartlens.application;

public enum ErrorCode {
	VALIDATION_ERROR,
	STREAM_NOT_FOUND,
	DUPLICATE_TRANSACTION_ID,
	WINDOW_NOT_READY,
	MINING_FAILED,
	RESULT_NOT_FOUND,
	COMPARISON_MISMATCH,
	STREAM_BUSY
}
