import { GitCompareArrows } from "lucide-react"
import { useApp } from "../../app/AppProvider"
import { Button, Card, EmptyState, ErrorBanner, PageHeading, formatNumber } from "../../components/ui"
import type { MiningRun } from "../../types/api"
const ResultCard = ({ label,run }: { label: string; run: MiningRun }) => <Card><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{run.patternCount}</p><p className="text-xs text-slate-500">patterns · {formatNumber(run.executionTimeMs)} ms</p></Card>
export default function ComparisonPage() {
  const { comparison,compare,status,error,overview,config } = useApp()
  const ready = (overview?.transactionCount ?? 0) >= config.paneSize * config.windowPaneCount
  const common = comparison?.oracle ?? comparison?.fwudsCt
  return <><PageHeading title="So sánh" description="Đối chiếu CT/DWT trên cửa sổ hoàn chỉnh gần nhất; Oracle dùng cho cửa sổ nhỏ." action={<Button onClick={() => void compare().catch(() => undefined)} disabled={!ready || status === "loading"}><GitCompareArrows size={17}/>{status === "loading" ? "Đang đối chiếu…" : "Chạy đối chiếu"}</Button>}/><ErrorBanner message={error}/>{!comparison ? <Card><EmptyState title="Chưa có dữ liệu đối chiếu" description={ready ? "Bấm Chạy đối chiếu để kiểm chứng kết quả." : "Window chưa đủ giao dịch theo cấu hình hiện tại."}/></Card> : <><div className={`mb-5 rounded-xl border p-4 ${comparison.equivalent ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-red-200 bg-red-50 text-red-800"}`}><p className="font-semibold">{comparison.equivalent ? comparison.oracleVerified ? "Oracle, CT và DWT cho kết quả tương đương" : "CT và DWT cho kết quả tương đương" : "Phát hiện sai khác"}</p><p className="mt-1 text-sm">{comparison.equivalent ? `Window #${comparison.fwudsCt.windowId}: đã đối chiếu pattern, WUS, support và transaction IDs.` : comparison.differences.join(" · ")}</p>{!comparison.oracleVerified && <p className="mt-2 text-xs">Oracle chỉ chạy khi có tối đa 16 item và 500 giao dịch. Window này được đối chiếu giữa hai thuật toán; chưa được Oracle xác nhận.</p>}</div><div className="grid gap-4 sm:grid-cols-3">{comparison.oracle && <ResultCard label="Oracle" run={comparison.oracle}/>}<ResultCard label="FWUDS-CT" run={comparison.fwudsCt}/><ResultCard label="FWUDS-DWT" run={comparison.fwudsDwt}/></div><Card className="mt-5"><h2 className="mb-4 font-semibold">Patterns ({common?.patternCount ?? 0})</h2><div className="flex flex-wrap gap-2">{common?.patterns.slice(0,200).map(pattern => <span key={JSON.stringify(pattern.items)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 font-mono text-xs">{`{${pattern.items.join(", ")}}`} <strong className="ml-2 text-blue-700">{formatNumber(pattern.wus)}</strong></span>)}</div>{(common?.patternCount ?? 0) > 200 && <p className="mt-3 text-xs text-slate-500">Hiển thị 200 pattern đầu; toàn bộ tập pattern đã được đối chiếu.</p>}</Card></>}</>
}
