import { test,expect } from "@playwright/test"
const api = process.env.CARTLENS_E2E_API || "http://localhost:8081/api/v1"
test.afterEach(async ({page,request}) => {
  const id = await page.evaluate(() => localStorage.getItem("cartlens.streamId")).catch(() => null)
  if (id) {
    const response = await request.get(`${api}/streams/${id}/replay`)
    if (response.status() === 200) {
      const job = await response.json()
      if (["RUNNING","PAUSED","PAUSING","STOPPING"].includes(job.state)) await request.post(`${api}/streams/${id}/replay/stop`)
    }
  }
})
test("DSe correctness, live Chainstore controls, history, export and reload", async ({ page,request }) => {
  const errors: string[] = []; page.on("pageerror",error => errors.push(error.message))
  const streamListRequests: string[] = []
  page.on("request", request => { if (request.method() === "GET" && /\/streams\/?$/.test(new URL(request.url()).pathname)) streamListRequests.push(request.url()) })
  await page.goto("/"); await expect(page.getByRole("heading",{name:"Tổng quan",exact:true})).toBeVisible()
  await expect(page.getByRole("button",{name:"Stream mới"})).toBeEnabled()
  await expect(page.getByLabel("Phiên dữ liệu đã lưu")).toHaveCount(0)
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await page.getByRole("button",{name:"Nạp DSe"}).click()
  await expect(page.getByRole("heading",{name:"Danh sách (6 giao dịch)"})).toBeVisible()
  const demoId = await page.evaluate(() => localStorage.getItem("cartlens.streamId"))
  const demoComparison = await request.post(`${api}/streams/${demoId}/comparisons`, { data: { paneSize: 2, windowPaneCount: 2, minWus: 0.5 } })
  expect(demoComparison.ok()).toBe(true)
  expect(await demoComparison.json()).toMatchObject({ equivalent: true, oracleVerified: true })
  await page.getByRole("button",{name:"Kết quả",exact:true}).click()
  await expect(page.getByText("#2",{exact:true})).toBeVisible()
  await page.getByRole("button",{name:"Lịch sử window"}).click()
  await expect(page.getByRole("button",{name:/#1 ·/})).toBeVisible()
  await page.getByRole("button",{name:/#1 ·/}).click()
  await expect(page.getByText("#1",{exact:true})).toBeVisible()
  await page.screenshot({path:"../tmp/ui-dse-results.png",fullPage:true})
  await page.getByRole("button",{name:"Tổng quan",exact:true}).click()
  const previousId = await page.evaluate(() => localStorage.getItem("cartlens.streamId"))
  await page.getByRole("button",{name:"Stream mới"}).click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem("cartlens.streamId"))).not.toBe(previousId)
  await expect(page.getByRole("button",{name:"Stream mới"})).toBeEnabled()
  const id = await page.evaluate(() => localStorage.getItem("cartlens.streamId"))
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await page.getByRole("button",{name:"Cấu hình luồng",exact:true}).click()
  await page.getByRole("button",{name:"Cấu hình Chainstore",exact:true}).click()
  await page.getByLabel("Số giao dịch muốn đọc").fill("12000")
  await page.getByRole("button",{name:"Bắt đầu Chainstore"}).click()
  await expect(page.getByRole("button",{name:"Tạm dừng",exact:true})).toBeVisible()
  await page.getByRole("button",{name:"Tạm dừng",exact:true}).click()
  await expect(page.getByText("Đã tạm dừng",{exact:true})).toBeVisible({timeout:15000})
  const before = await (await request.get(`${api}/streams/${id}/overview`)).json()
  await page.waitForTimeout(250)
  const after = await (await request.get(`${api}/streams/${id}/overview`)).json()
  expect(after.transactionCount).toBe(before.transactionCount)
  await page.reload()
  await expect(page.getByRole("button",{name:"Stream mới"})).toBeEnabled()
  expect(await page.evaluate(() => localStorage.getItem("cartlens.streamId"))).toBe(id)
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await expect(page.getByText("Đã tạm dừng",{exact:true})).toBeVisible()
  await page.getByRole("button",{name:"Tiếp tục",exact:true}).click()
  await expect(page.getByText("Hoàn tất",{exact:true})).toBeVisible({timeout:45000})
  const final = await (await request.get(`${api}/streams/${id}/overview`)).json()
  expect(final.transactionCount).toBe(12000); expect(final.latestRun.windowId).toBe(9)
  expect(final.metrics.retainedTransactions).toBe(4000); expect(final.metrics.processedTransactions).toBe(12000)
  await page.getByRole("button",{name:"Trang sau",exact:true}).click()
  await expect(page.getByRole("button",{name:"Chi tiết giao dịch 101",exact:true})).toBeVisible()
  await page.getByRole("button",{name:"Trang trước",exact:true}).click()
  await expect(page.getByRole("button",{name:"Chi tiết giao dịch 1",exact:true})).toBeVisible()
  await page.getByRole("button",{name:"Làm mới",exact:true}).count().then(async count => { if (count) await page.getByRole("button",{name:"Làm mới",exact:true}).click() })
  await page.screenshot({path:"../tmp/ui-chainstore-controls.png",fullPage:true})
  await page.getByRole("button",{name:"Kết quả",exact:true}).click()
  await expect(page.getByText("#9",{exact:true})).toBeVisible()
  await page.getByRole("button",{name:"Lịch sử window"}).click()
  await expect(page.getByRole("button",{name:/#9 ·/})).toBeVisible()
  const downloaded = page.waitForEvent("download")
  await page.getByRole("link",{name:"Xuất CSV toàn phiên"}).click()
  await (await downloaded).saveAs("../tmp/ui-chainstore-results.csv")
  const chainstoreComparison = await request.post(`${api}/streams/${id}/comparisons`, { data: final.configuration.config })
  expect(chainstoreComparison.ok()).toBe(true)
  expect(await chainstoreComparison.json()).toMatchObject({ equivalent: true, oracleVerified: false })
  expect(streamListRequests).toEqual([])
  expect(errors).toEqual([])
})
test("mobile navigation and Chainstore form remain usable without page overflow", async ({ page }) => {
  await page.setViewportSize({width:390,height:844}); await page.goto("/")
  await expect(page.getByRole("button",{name:"Stream mới"})).toBeEnabled()
  await page.getByRole("button",{name:"Mở menu"}).click()
  await expect(page.getByRole("navigation").getByRole("button")).toHaveCount(3)
  await expect(page.getByRole("button",{name:"So sánh",exact:true})).toHaveCount(0)
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await expect(page.getByRole("heading",{name:"Luồng Chainstore"})).toBeVisible()
  await page.screenshot({path:"../tmp/ui-mobile-chainstore.png",fullPage:true})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test("chosen algorithm mines arriving panes and updates the UI without a run request", async ({ page,request }) => {
  const created = await request.post(`${api}/streams`)
  const { streamId } = await created.json()
  await page.addInitScript(id => localStorage.setItem("cartlens.streamId",id),streamId)
  const runRequests: string[] = []
  page.on("request",request => { if (request.method() === "POST" && request.url().includes("/runs")) runRequests.push(request.url()) })
  await page.goto("/")
  await expect(page.getByRole("button",{name:"Stream mới"})).toBeEnabled()
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await page.getByRole("button",{name:"Cấu hình luồng",exact:true}).click()
  await page.getByLabel("Kích thước pane").fill("2")
  await page.getByLabel("Số pane trong window").fill("2")
  await page.getByLabel("Ngưỡng minWus").fill("1")
  await page.getByRole("radio",{name:/FWUDS-CT/}).check()
  await page.getByRole("button",{name:"Lưu cấu hình",exact:true}).click()
  await expect(page.getByText(/Thuật toán đang áp dụng: FWUDS-CT/)).toBeVisible()
  const initial = await (await request.get(`${api}/streams/${streamId}/overview`)).json()
  expect(initial.latestRun).toBeNull()
  const session = initial.configuration.sessionId
  await page.getByLabel("Tốc độ giao dịch/giây").fill("5")
  await page.getByLabel("Số giao dịch muốn đọc").fill("40")
  await page.getByRole("button",{name:"Bắt đầu Chainstore",exact:true}).click()
  // The table starts empty and fills while replay is running, without a manual refresh.
  await expect(page.locator("tbody tr").first().locator("td").first()).toHaveText("1")
  expect((await (await request.get(`${api}/streams/${streamId}/replay`)).json()).state).toBe("RUNNING")
  await page.getByRole("button",{name:"Kết quả",exact:true}).click()
  await expect.poll(async () => (await (await request.get(`${api}/streams/${streamId}/overview`)).json()).latestRun?.windowId ?? 0).toBeGreaterThan(0)
  await expect(page.getByTestId("stream-live-status").getByText("FWUDS-CT",{exact:true})).toBeVisible()
  const first = await (await request.get(`${api}/streams/${streamId}/overview`)).json()
  await expect.poll(async () => (await (await request.get(`${api}/streams/${streamId}/overview`)).json()).latestRun?.windowId ?? 0).toBeGreaterThan(first.latestRun.windowId)
  await expect.poll(async () => (await (await request.get(`${api}/streams/${streamId}/replay`)).json()).state,{timeout:20000}).toBe("COMPLETED")
  await expect(page.getByText("#19",{exact:true})).toBeVisible()
  const final = await (await request.get(`${api}/streams/${streamId}/overview`)).json()
  expect(final.latestRun.algorithm).toBe("FWUDS_CT")
  expect(final.configuration.sessionId).toBe(session)
  expect(final.metrics.processedTransactions).toBe(40)
  expect(final.metrics.bufferedTransactions).toBe(0)
  expect(runRequests).toEqual([])
})

test("pause, edit, apply, continue and restart preserve run snapshots and original utilities", async ({ page,request }) => {
  const { streamId } = await (await request.post(`${api}/streams`)).json()
  await page.addInitScript(id => localStorage.setItem("cartlens.streamId",id),streamId)
  const errors: string[] = []; page.on("pageerror",error => errors.push(error.message))
  const runRequests: string[] = []
  page.on("request",r => { if (r.method() === "POST" && r.url().includes("/runs")) runRequests.push(r.url()) })
  await page.goto("/")
  await expect(page.getByRole("button",{name:"Stream mới"})).toBeEnabled()
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await page.getByRole("button",{name:"Cấu hình luồng",exact:true}).click()
  await page.getByRole("radio",{name:"FWUDS-CT",exact:true}).check()
  await page.getByLabel("Kích thước pane").fill("2")
  await page.getByLabel("Số pane trong window").fill("2")
  await page.getByLabel("Ngưỡng minWus").fill("1")
  await page.getByLabel("Tốc độ giao dịch/giây").fill("10")
  await page.getByLabel("Số giao dịch muốn đọc").fill("80")
  await page.getByRole("button",{name:"Bắt đầu Chainstore",exact:true}).click()
  await expect(page.getByLabel("Kích thước pane")).toBeDisabled()
  await expect(page.getByRole("combobox",{name:"Trọng số",exact:true})).toHaveCount(0)
  await expect(page.getByLabel("Giao dịch mỗi batch")).toHaveCount(0)
  await expect(page.getByLabel("Seed tái hiện")).toHaveCount(0)
  const running = await (await request.get(`${api}/streams/${streamId}/replay`)).json()
  expect(running.request.algorithm).toBe("FWUDS_CT")
  expect(running.request.paneSize).toBe(2)
  expect(running.request.weightMode).toBe("PROVIDED_UTILITY")
  await expect.poll(async () => (await (await request.get(`${api}/streams/${streamId}/overview`)).json()).transactionCount).toBeGreaterThanOrEqual(9)
  await page.getByRole("button",{name:"Tạm dừng",exact:true}).click()
  await expect(page.getByText("Đã tạm dừng",{exact:true})).toBeVisible()
  const before = await (await request.get(`${api}/streams/${streamId}/overview`)).json()
  await page.getByRole("radio",{name:"FWUDS-DWT",exact:true}).check()
  await page.getByLabel("Kích thước pane").fill("3")
  await page.getByLabel("Số pane trong window").fill("3")
  await page.getByLabel("Ngưỡng minWus").fill("0.9")
  await expect(page.getByRole("button",{name:"Tiếp tục",exact:true})).toBeDisabled()
  await page.getByRole("button",{name:"Kết quả",exact:true}).click()
  await page.waitForTimeout(1200)
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await page.getByRole("button",{name:"Cấu hình luồng",exact:true}).click()
  await expect(page.getByLabel("Kích thước pane")).toHaveValue("3")
  await page.getByRole("button",{name:"Áp dụng",exact:true}).click()
  await expect(page.getByTestId("run-configuration")).toContainText("phiên bản 2")
  await expect(page.getByRole("button",{name:"Tiếp tục",exact:true})).toBeEnabled()
  const applied = await (await request.get(`${api}/streams/${streamId}/overview`)).json()
  expect(applied.transactionCount).toBe(before.transactionCount)
  expect(applied.configuration.algorithm).toBe("FWUDS_DWT")
  expect((await (await request.get(`${api}/streams/${streamId}/replay`)).json()).request.weightMode).toBe("PROVIDED_UTILITY")
  expect(applied.configuration.sessionId).not.toBe(before.configuration.sessionId)
  expect(applied.metrics.bufferedTransactions).toBe(before.transactionCount % 3)
  const oldHistory = await (await request.get(`${api}/streams/${streamId}/results?sessionId=${before.configuration.sessionId}`)).json()
  expect(oldHistory.length).toBeGreaterThan(0)
  await page.reload()
  await expect(page.getByRole("button",{name:"Stream mới"})).toBeEnabled()
  await page.getByRole("button",{name:"Giao dịch",exact:true}).click()
  await page.getByRole("button",{name:"Cấu hình luồng",exact:true}).click()
  await expect(page.getByLabel("Kích thước pane")).toHaveValue("3")
  await expect(page.getByTestId("run-configuration")).toContainText("FWUDS-DWT")
  await page.getByRole("button",{name:"Tiếp tục",exact:true}).click()
  await expect.poll(async () => (await (await request.get(`${api}/streams/${streamId}/overview`)).json()).transactionCount).toBeGreaterThan(before.transactionCount + 3)
  await page.getByRole("button",{name:"Tạm dừng",exact:true}).click()
  await expect(page.getByText("Đã tạm dừng",{exact:true})).toBeVisible()
  const checkpoint = await (await request.get(`${api}/streams/${streamId}/overview`)).json()
  await page.getByLabel("Sau khi áp dụng").selectOption("RESTART")
  await page.getByLabel("Tốc độ giao dịch/giây").fill("0")
  await page.getByLabel("Số giao dịch muốn đọc").fill("20")
  await expect(page.getByLabel("Sau khi áp dụng")).toHaveValue("RESTART")
  await page.getByRole("button",{name:"Áp dụng",exact:true}).click()
  await expect(page.getByRole("button",{name:"Restart",exact:true})).toBeEnabled()
  const nextId = await page.evaluate(() => localStorage.getItem("cartlens.streamId"))
  expect(nextId).not.toBe(streamId)
  expect((await (await request.get(`${api}/streams/${nextId}/overview`)).json()).transactionCount).toBe(0)
  expect((await (await request.get(`${api}/streams/${streamId}/overview`)).json()).transactionCount).toBe(checkpoint.transactionCount)
  await page.screenshot({path:"../tmp/ui-run-configuration-paused.png",fullPage:true})
  await page.getByRole("button",{name:"Restart",exact:true}).click()
  await expect(page.getByText("Hoàn tất",{exact:true})).toBeVisible()
  const final = await (await request.get(`${api}/streams/${nextId}/overview`)).json()
  expect(final.transactionCount).toBe(20)
  expect(final.latestRun.algorithm).toBe("FWUDS_DWT")
  expect((await (await request.get(`${api}/streams/${nextId}/replay`)).json()).request.weightMode).toBe("PROVIDED_UTILITY")
  const tx = await (await request.get(`${api}/streams/${nextId}/transactions`)).json()
  expect(tx[0].id).toBe("1")
  expect(tx[0].items[0]).toMatchObject({ itemId: "1834", quantity: 1, weight: 173038 })
  expect(new Set(tx.map((t: {id:string}) => t.id)).size).toBe(20)
  expect(errors).toEqual([]); expect(runRequests).toEqual([])
})

test("a legacy synthetic replay requires a separate stream to switch to original utility", async ({ page,request }) => {
  const { streamId } = await (await request.post(`${api}/streams`)).json()
  const started = await request.post(`${api}/streams/${streamId}/replay`, { data: {
    algorithm: "FWUDS_DWT", paneSize: 2, windowPaneCount: 2, minWus: 1,
    transactionsPerSecond: 5, maxTransactions: 80, weightMode: "SYNTHETIC_BATCH", weightBatchSize: 5, seed: 42,
  } })
  expect(started.ok()).toBe(true)
  await expect.poll(async () => (await (await request.get(`${api}/streams/${streamId}/overview`)).json()).transactionCount).toBeGreaterThanOrEqual(3)
  expect((await request.post(`${api}/streams/${streamId}/replay/pause`)).ok()).toBe(true)
  await expect.poll(async () => (await (await request.get(`${api}/streams/${streamId}/replay`)).json()).state).toBe("PAUSED")
  const checkpoint = await (await request.get(`${api}/streams/${streamId}/overview`)).json()
  await page.addInitScript(id => localStorage.setItem("cartlens.streamId", id), streamId)
  await page.goto("/")
  await expect(page.getByRole("button", { name: "Stream mới", exact: true })).toBeEnabled()
  await page.getByRole("button", { name: "Giao dịch", exact: true }).click()
  await page.getByRole("button", { name: "Cấu hình luồng", exact: true }).click()
  await expect(page.getByRole("combobox", { name: "Trọng số", exact: true })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Tiếp tục", exact: true })).toBeDisabled()
  await expect(page.getByLabel("Sau khi áp dụng")).toHaveValue("RESTART")
  await expect(page.getByLabel("Sau khi áp dụng")).toBeDisabled()
  await page.getByLabel("Tốc độ giao dịch/giây").fill("0")
  await page.getByLabel("Số giao dịch muốn đọc").fill("20")
  await page.getByRole("button", { name: "Áp dụng", exact: true }).click()
  await expect(page.getByRole("button", { name: "Restart", exact: true })).toBeEnabled()
  const nextId = await page.evaluate(() => localStorage.getItem("cartlens.streamId"))
  expect(nextId).not.toBe(streamId)
  const nextReplay = await (await request.get(`${api}/streams/${nextId}/replay`)).json()
  expect(nextReplay.request.weightMode).toBe("PROVIDED_UTILITY")
  expect((await (await request.get(`${api}/streams/${streamId}/overview`)).json()).transactionCount).toBe(checkpoint.transactionCount)
  await page.getByRole("button", { name: "Restart", exact: true }).click()
  await expect(page.getByText("Hoàn tất", { exact: true })).toBeVisible()
  const tx = await (await request.get(`${api}/streams/${nextId}/transactions`)).json()
  expect(tx[0].items[0]).toMatchObject({ itemId: "1834", quantity: 1, weight: 173038 })
})
